# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stephen Yang
name: Jiezhi "Stephen" Yang
position: Student 
email: stephenyang@berkeley.edu
description: >-
  I am a second year Master's student in Computational Science Engineering at [Harvard University](https://www.harvard.edu/), cross-registered at [MIT](https://www.mit.edu/). I received my B.A. in Computer Science and Cognitive Science from [UC Berkeley](https://www.berkeley.edu/), where I graduated from the [EECS Honors Program](https://eecs.berkeley.edu/resources/undergrads/honors) with high distinction.

  
  I am interested in 3D vision and embodied intelligence. At Berkeley, I was fortunate to work at [RISE](https://rise.cs.berkeley.edu/) and [BAIR](https://bair.berkeley.edu/) Lab under Prof. [Joseph Gonzalez](https://people.eecs.berkeley.edu/~jegonzal/) and [Trevor Darrell](https://people.eecs.berkeley.edu/~trevor/), with Ph.D. candidate [Charles Packer](https://people.eecs.berkeley.edu/~cpacker/), [Lisa Dunlap](https://www.lisabdunlap.com/), and [Alvin Wan](https://alvinwan.com/). I also appreciate my experience beiefly collaborating with [Harvard CVG](https://vcg.seas.harvard.edu/), [Interactive Robotics Group](https://computationalrobotics.seas.harvard.edu/) and [MIT CSAIL](https://www.csail.mit.edu/).
  
  
  I am on the job market for 2025 New Grad opportunities. Please contact me at stephenyang[AT]berkeley[DOT]edu!

misc: >-
  I was born in the beautiful, German-style coastal city of [Tsingtao](https://en.wikipedia.org/wiki/Qingdao). I like VR games and photography, espacially aerial photography with drones. I am also trying to improve my very much out of practice piano skills...  

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephenjyang.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Stepenyang
github_username: StephenYangjz
google_scholar: BzyVxVUAAAAJ
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
